### ISSUE TITLE
MigrationVersions subfolders

### ISSUE THREAD

**Issue by Specthram** [kaliop-uk/ezmigrationbundle#140]
Hi there :)
If we have many migrations .yml files, it could be great to put them in subfolders. What do you think about it ? At this moment, subfolders are just ignored. Or maybe I missed something ? Is it a possibility to add this functionality ? (I use 3.6.3)
Thanks ! :+1:

**Comment by gggeek** [comment]
Hello.
It is possible to alter the service which scans for migrations to look into subfolders. I even have code ready for that that I could easily add to the bundle.
But there are a few constraints to consider:

1. making the bundle scan subfolders by default would be a ABC break, as if currently people keep other stuff in subfolders, that other stuff would start to be picked up as migrations, and give unexpected results

2. we could use a cli switch to enable the scanning of subfolders, but I am a bith loath to do that, as I do not want to have a million cli switches for every possible thing. Also, the code that deals with finding out if the cli tools take a path to a dir, a path to a file or a migration name is already ugly enough for me not to try to make it smarter

3. the 'scan for subfolders' option would thus be activated by changing one symfony parameter with the name of the php class used to load the migrations

4. I would prefer to implement this in version 4.4 rather than 3.7

Would that be ok with you ?

**Comment by gggeek** [comment]
ps: early implementation: https://github.com/kaliop-uk/ezmigrationbundle/commit/4f56c0d2aa8008cc944c481f2b5eba0e518a0036

**Comment by Specthram** [comment]
thank you for your quick answer. I understand what you said and I take note. It's not a hurry on my side. (by the way I upgraded to 4.3.0 for tags functionalities).

**Comment by gggeek** [comment]
:-)

**Comment by gggeek** [comment]
Implemented in 4.4

Btw, there is also a `mass_migrate` command that you might want to play around with
