### ISSUE TITLE
Allow refering to migrations by shortname to migration

### ISSUE THREAD

**Issue by andrerom** [kaliop-uk/ezmigrationbundle#152]
Either:
- allow usage of short name of migration when calling `migration` and possible other places
- or, add option on status to get full path in table

**Comment by andrerom** [comment]
Hmm, seems short name is what is supposed to be used if migration is in src, but in case of stuff in vendor full path needs to be provided. Is that correct? Seems a bit inconsistent, would be easier to start using if not   ;)

**Comment by gggeek** [comment]
Hello and happy 2018!

Actually NotABug (TM).
But I agree that the current situation looks inconsistent...

The fact is that there is a lot of history here:
- bundle started out by scanning a specific set of folders in all bundles
- then I realized that devs might want to store migration in other places (eg 'ezpublish/Migrations')
- and since those other places are highly variable, I decided to make it flexible and easy to use *any* desired path by just putting it as command-line option (instead of going, say, for setings)
- while keeping it backwards compatible (if no path given on cli, std set of folders is scanned)
Also, keep in mind that when migration is in the db table, we can identify it by its short name (hence the --delete support). But when it is not, we can only identify it by short name if it is in the std set of folders.

Last but not least, the code dealing with reconciliation of paths and migration status is already a horrible mess, so I am a bit loath to make it even more smart/flexible.

This long exposition is to give you an overview of where we stand today.

I am open to ideas/suggestions/requests, just they should be more specific than 'allow usage of short migration name everywhere'...

As a side note: the 'migration info' command will give you already the full path of a migration recorded in the db table

**Comment by gggeek** [comment]
Maybe it gets less confusing if you start thinking about 'migrations' as the executed entities, and 'migration defs' as the files where we define what to do ?
After that it seems intuitive that migratinos can be referenced by shortname, while mig defs by full path...
(I could have created a separate 'migration_definition' command to make this more evident, but a) I thought that devs are lazy and wouldnt like it, and b) some commands do have to deal with both entities at the same tyme anyway (notably 'status' and 'migrate')...

**Comment by gggeek** [comment]
ps: not scanning all of 'vendor' bundles for migrations by default but only 'src' ones is also kind of a safety feature...

**Comment by gggeek** [comment]
pps: I agree that having a '--verbose' flag for status to print the full path of each migration could be a nice complement to the existing 'info' command

**Comment by gggeek** [comment]
Implemented; will be in 5.14. New option for `status` command: `--show-path`
