### ISSUE TITLE
please support "ezsystems/ezplatform-kernel: ^1.0"

### ISSUE THREAD

**Issue by videni** [kaliop-uk/ezmigrationbundle#236]

**Comment by gggeek** [comment]
Is this the same as #218 ?

**Comment by videni** [comment]
@gggeek , I don't thinks so, there is [one](https://github.com/ezsystems/ezmigrationbundle) forked by ezsystems, seems it can work with ezsystems/ezplatform-kernel.

**Comment by gggeek** [comment]
ezsystems/ezplatform-kernel is the "kernel package" powering "ezplatform 3", so this definitely feels like a duplicate bug.

As for the fork from ezsystems: I have not received any PR from that repo since April - most likely because the eZ devs got tired of waiting from me :-( Also, it says on the tin "Internal fork of kaliop migration bundle for use in our demos. It is not supported and will be completely replaced in the future. ", so use it with a grain of salt...
