### ISSUE TITLE
Allow re-execution of only one migration definition

### ISSUE THREAD

**Issue by crevillo** [kaliop-uk/ezmigrationbundle#36]
Suppose you are working in a bundle with 20 or 200 yml definitions. it would be good to have a way to retry just one of them. Maybe passing the name of the file as argument to the command?

**Comment by gggeek** [comment]
q: what if the migration is already flagged as 'done'?
I was thinking along the line of: if the migration is specified, and it is alredy done
- fail by default with a message 'was already done'
- support a cli switch 'please-redo'

**Comment by crevillo** [comment]
good points.

**Comment by gggeek** [comment]
In fact passing the filename using the --path option already works, and is documented since 2.0.0beta-5

It will behave just as it behaves when executing many migrations - if you want to retry a failed/executed migration you can delete it with the 'migration --delete' command then retry it.

All that is left is to improve the output of the status command when a path is passed in to not list all executed migrations but only executed-migrations which match the path
