### ISSUE TITLE
Migration aborted causing by corrupted unused drafts

### ISSUE THREAD

**Issue by ramzi-arfaoui** [kaliop-uk/ezmigrationbundle#87]
During execution of the migration bundle the script will fail because of existing corrupted drafts in the database.
I have tried to add new FieldType to an existing contenttype in a large database, where after some years of production some corrupted drafts are available !
This drafts just only have an contentobject but no attributes and the migration script will collect all object information first and this cause an error during running the script.

_Migration aborted! Reason: Error in execution of step 1: The expression ' OR ' expected at least 1 argument but none provided. in file  .....eZ/Publish/Core/Persistence/Doctrine/DoctrineExpression.php line 74_

I think it should be checked first if object attributes exist.

**Comment by gggeek** [comment]
Hello.
Thanks for reporting this.
However, I am not sure that it is the duty of the migration bundle to check the coherency of the database before attempting to run a migration.

There are many ways that the db can become corrupted over time (especially databases that started out with ez4 and custom import scripts), and it is practically impossible to know beforehand which types of errors will be the results of which db inconsistency. F.e. your problem might be fixed in a future version of the ezp kernel, and then the check within the migration bundle would become redundant or even harmful.
Also, checking the database for consistency can take a very long time, and I don't think that we should penalize every single execution just to fix some rare cases.

There is a separate extension (ez4 at the moment, but I plan to port it to ez5 some day) available, which was built for the specific purpose of finding any problem with data consistency: ezdbintegrity.
The current workflow I recommend for 'big migration' projects is:
- run ezdbintegrity checks
- look by hand at results, and fix as many errors reported as possible
- then do your migration

If you are ok with this, I will close this ticket as wont-fix.

**Comment by ramzi-arfaoui** [comment]
Hello,
the workflow you described is similar to what I also have done to fix the migration process. I had to fix big databases with over 10k content objects. Every time was the same issue that draft could not be processed.
I think this is not only related to custom implementations or rare cases. The Backend Editor can create a lot of drafts or just not properly discard changes and at some point, the user will be deactivated or deleted. What remains over the years is just trashes in the DB. This behaviour affects eZ4 and eZ5 Installations.
We have just to keep it in mind if someone gets the same issue during the migration.
Thanks
